version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
  - dependabot
