AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/*
    - bundle/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - /*.gemspec

Metrics/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes
